import PageHeader from "@/components/PageHeader";
import PageFooter from "@/components/PageFooter";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PageHeader />
        {children}
        <PageFooter />
      </body>
    </html>
  );
}
